### ISSUE TITLE
Ping me

### ISSUE THREAD

**Issue by dosten** [ringcaptcha/widget#30]
Hi! I'm the previous maintainer of this widget, can someone ping me on my email? (Your can find it on my GitHub profile) @nethsix I can't find your email on your GitHub profile. Thanks.

**Comment by yutaf** [comment]
Hi @dosten , I am Yuta from Xenon Ventures. Now I am working for RingCaptcha.
Sorry for not replying to your message. We haven't noticed this.
My email is yuta@ringcaptcha.com .
Please let me know if you still have something to notify to us.

By the way, I think you still have a few ownerships for RingCaptcha related services like
https://packagist.org/packages/ringcaptcha/

I have seen the documentation for RingCaptcha other than Packagist before somewhere... but I cannot find it on the internet now.

Can you transfer the ownerships to us?
Thanks.

**Comment by dosten** [comment]
Hi @yutaf, don't worry, tell me your packagist username and I can add you as a maintainer and delete my self.

**Comment by yutaf** [comment]
Thank you @dosten ! The username is "ringcaptcha".

**Comment by dosten** [comment]
@yutaf done!

**Comment by yutaf** [comment]
Thank you for your help, @dosten !
